### ISSUE TITLE
connect-src for Google Analytics

### ISSUE THREAD

**Issue by milgner** [jonashaag/content-security-policy-rules#2]
I also had to add it to `connect-src` for Google Analytics to work. Can you confirm?

**Comment by jonashaag** [comment]
You're sure it's for GA? Can you show the CSP violation error message? (But I guess it's safe to add anything from Google to connect-src...)

**Comment by milgner** [comment]
I don't have the message anymore but I'll try reproducing it over the weekend. It was really bugging me because I didn't include Google in my `default-src` and since I didn't have `connect-src` before that, the error message was very confusing. After adding `connect-src` with `www.google-analytics.com`, it worked.

**Comment by localpcguy** [comment]
I've seen this as well, although I'm not currently seeing it. I'm wondering if Google was experimenting with something which caused the CSP error and then rolled it back?

**Comment by nico3333fr** [comment]
I've also noticed some connect-src issues for Google Analytics in my CSP reports, but no more details.

**Comment by jonashaag** [comment]
Ok let's add this to the rules then. PR welcomed
